### ISSUE TITLE
misspelled word in about section

### ISSUE THREAD

**Issue by keshavsingh3197** [khyatijha777/cpp#7]
'k' is missing in both wrods
```
  ❌                          ✅       
hactoberfest            hacktoberfest
hactoberfest2020        hacktoberfest2020
```

**Comment by testerslol123** [comment]
Hi, I see, there's some mis typo word in this repo. I would like to take on this.
@khyatijha777 Could assign me this task to fix some missing typo word?

**Comment by khyatijha777** [comment]
@testerslol123 Hi, This repo is just for revision of C++ syntax, Spelling is not at all a concern here. 
If you are a begginer on github then for learning purpose, you can create one PR with some typo correction.  
But I suggest you to write some code.
